version: '3.8'

services:
  postgres:
    image: postgres:15
    container_name: postgres_exercice8
    environment:
      POSTGRES_USER: your_username
      POSTGRES_PASSWORD: your_password
      POSTGRES_DB: webflux_exercice8
    ports:
      - "5432:5432"

volumes:
  postgres_data:
    driver: local